= Demo for testing Confluent Cloud on Azure via private link

This demonstrates how to use Confluent Cloud on Azure via private link

DISCLAIMER: This project is for demonstration purposes only. Using the demo unmodified in production is highly discouraged. Use at your own risk.

## Precondition

You need the following to run this demo:

* A Confluent Cloud Organization
* A Confluent Cloud API Key with sufficient access permissions to set up a dedicated cluster
* An Azure account with sufficient access

## Getting started


### Base Networking with Terraform (optional)
You can start by setting up your base networking. Just enter `terraform/1-base-networking` and 
set/customize some variables by copying `terraform.tfvars.template` to `terraform.tfvars`.

Afterwards run:

```shell
terraform init
```

Then run:

```shell
terraform plan
```

In this demo, we will set up a VPN gateway. This will allow you to create a connection to the newly created VNet on Azure and allows you to create cluster-specific resources with terraform. That wouldn't be possible otherwise as we are setting up a dedicated cluster with private networking.


### Confluent Cloud Dedicated cluster with Private Link

Now enter the folder `terraform/2-dedicated-cluster-with-private-link`.
Set/customize some variables by copying `terraform.tfvars.template` to `terraform.tfvars`.
Make sure the name of the resource group, and the other Azure settings match the ones you used in the previous step.

Open a shell and change into the `terraform` subfolder. In order to use your Confluent Cloud service account, either put your `api.txt` into that folder, or set the following environment variables to your API key:

```shell
export CONFLUENT_CLOUD_API_KEY="PUT YOUR API KEY HERE"
export CONFLUENT_CLOUD_API_SECRET="PUT YOUR API SECRET HERE"
```

If you start from scratch, initialize terraform once:

```shell
terraform init
```

Set 

Check the plan generated by terraform:

```shell
terraform plan
```

If you agree with the plan, deploy the resources (that will take some time):

```shell
terraform apply
```

Setting up the resources will take a long time. Grab several coffees and relax.

### Custom DNS split routing

If terraform finished successfully your cluster should be ready and a private link connectivity should work in principle. However, to make it work through your VPN tunnel, some extra work needs to be done.

Please find a pre-configured openvpn config file in the subfolder `terraform/1-base-networking(generated/openvpn_config_files`. Unfortunately, this needs to completed manually. For this, go to the newly created virtual network gateway in your Azure resource group, open `Settings` and `Point-to-site configuration`. Get the configuration by clicking on "Download VPN client". You can either use the file openvpn config found in that zip file directly or pick the hostname and the pre-shared key out of it and complete the pre-configured config file created by terraform with it.

Then, if you are on Ubuntu (used in this demo). Copy the result to `/etc/openvpn/aws.conf` and install openvpn and its helper script for dns resolution:

```shell
sudo apt install openvpn openvpn-systemd-resolved
```

Then start the vpn connection:

```shell
systemctl start openvpn@aws
```

You should now be able to use a direct connection to your Azure VNet. Check if DNS is forwarded to your Azure resolver for the confluent cloud bootstrap server and broker hostnames:

```shell
resolvectl status
```

You should see a custom domain server on the other end of your VPN connection being used for the particular subdomain used by your confluent cloud cluster.
DNS resolution is forwarded to the standard Azure resolver automatically. The setup has configured that domain as custom domain for your VNet. The IP addresses point to your private link endpoints.

### Create resources in your dedicated cluster with Terraform

If you have established a connection to your dedicated cluster via OpenVPN on the machine where you run Terraform, you can now create some test resources in that cluster by running the terraform code in `terraform/3-cluster-resources`.

### Re-distribute your private link access to your dedicated cluster on Azure with your own private link service

This step has not been automated for time reasons. Please follow the steps in `terraform/5-load-balancer-nginx/README.adoc`.

== Testing the setup

Please open a shell and enter the directory `terraform/3-cluster-resources/generated`.

Have a look at the config files pre-configured for you.

You can for example start producing to the new cluster like this (from a VM in the same VNet on Azure):

```shell
kafka-console-producer --producer.config client-clientReadWrite.conf --bootstrap-server <your-bootstrap-server:9092> --topic test
```

### 

== Wrapping things up

Destroy all manually created resources first. Then you can destroy all automatically created resources including the cluster in Confluent Cloud by running the following command:

```shell
terraform destroy
```
