= Demo for testing Confluent Cloud on Azure via private link

This demonstrates how to use Confluent Cloud on Azure via private link

DISCLAIMER: This project is for demonstration purposes only. Using the demo unmodified in production is highly discouraged. Use at your own risk.

## Precondition

You need the following to run this demo:

* A Confluent Cloud Organization
* A Confluent Cloud API Key with sufficient access permissions to set up a dedicated cluster
* An Azure account with sufficient access

## Getting started

Set/customize some variables by copying `terraform.tfvars.template` to `terraform.tfvars`.

Open a shell and change into the `terraform` subfolder. In order to use your Confluent Cloud service account, either put your `api.txt` into that folder, or set the following environment variables to your API key:

```shell
export CONFLUENT_CLOUD_API_KEY="PUT YOUR API KEY HERE"
export CONFLUENT_CLOUD_API_SECRET="PUT YOUR API SECRET HERE"
```

If you start from scratch, initialize terraform once:

```shell
terraform init
```

Set 

Check the plan generated by terraform:

```shell
terraform plan
```

If you agree with the plan, deploy the resources (that will take some time):

```shell
terraform apply
```

== Testing the setup

Please open a shell and enter the directory `terraform/generated`.

Have a look at the config files pre-configured for you.

You can for example start producing to the new cluster like this (from a VM in the same VNet on Azure):

```shell
kafka-console-producer --producer.config client-clientReadWrite.conf --bootstrap-server <your-bootstrap-server:9092> --topic test
```

== Wrapping things up

You can destroy all created resources including the cluster in Confluent Cloud by running the following command:

```shell
terraform destroy
```
